/**
 * Underwritten Properties (underwritten.html): shared state, data, saved
 * edits, filters and the property models the map, panel and cards read.
 *
 * Data (all generated by scripts/build_underwritten.py, never hand-edited):
 *   data/comps.json        923 entire-home Airbnb listings with the main page's areas, beach position, tiers
 *   data/shoreline.json    the Gulf shoreline points the notebooks measure to
 *   data/underwritten.json the underwriting sheets, grouped into properties and versions, plus the validation report
 * Edits and new listings live in localStorage (wrapped in try/catch) and can be
 * exported to data/underwritten_local.json, which the build merges in for everyone.
 *
 * Existing properties show the sheet's own numbers; recalculated numbers
 * (UWMath.compute) appear only once a financial input is edited. Comps only
 * ever come from the workbook; revenue cases are only ever set by the user.
 */
/* global UWMath, UWGeo, UWCsv */
(function () {
  const UW = (window.UW = {});
  UW.VERSION = "20261010-uw2";
  const LS_KEY = "galvestonUW.v1";

  // ---------------------------------------------------------------------------
  // Formatting
  // ---------------------------------------------------------------------------
  const isNum = (v) => v != null && v !== "" && !isNaN(v) && isFinite(v);
  UW.fmt = {
    money: (n) => (isNum(n) ? (n < 0 ? "−$" : "$") + Math.abs(Math.round(n)).toLocaleString("en-US") : "—"),
    money2: (n) => (isNum(n) ? "$" + Number(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : "—"),
    k: (n) => {
      if (!isNum(n)) return "—";
      const a = Math.abs(n), s = n < 0 ? "−$" : "$";
      return a >= 999500 ? s + (a / 1e6).toFixed(2).replace(/0$/, "") + "M" : s + Math.round(a / 1000) + "k";
    },
    pct: (v, d) => (isNum(v) ? (v * 100).toFixed(d == null ? 2 : d).replace("-", "−") + "%" : "—"),
    num: (v) => (isNum(v) ? String(Math.round(v * 100) / 100) : "—"),
    x: (v) => (isNum(v) ? Number(v).toFixed(2) + "×" : "—"),
    mi: (d) => (!isNum(d) ? "—" : d < 0.095 ? Math.round((d * 5280) / 10) * 10 + " ft" : d.toFixed(d < 10 ? 2 : 1) + " mi"),
    km: (d) => (!isNum(d) ? "—" : d < 1 ? Math.round(d * 100) * 10 + " m" : d.toFixed(2) + " km"),
    beds: (b) => (!isNum(b) ? "—" : b === 0 ? "Studio" : UW.fmt.num(b) + "BR"),
  };
  UW.isNum = isNum;
  UW.esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]);
  UW.clone = (o) => (o == null ? o : JSON.parse(JSON.stringify(o)));
  const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);

  // ---------------------------------------------------------------------------
  // Events
  // ---------------------------------------------------------------------------
  const handlers = {};
  UW.on = (ev, fn) => (handlers[ev] = handlers[ev] || []).push(fn);
  UW.emit = (ev, data) => (handlers[ev] || []).forEach((fn) => fn(data));

  // ---------------------------------------------------------------------------
  // Constants
  // ---------------------------------------------------------------------------
  UW.AMENITIES = [["pool", "Pool"], ["pool_heater", "Heated pool"], ["hot_tub", "Hot tub"], ["game_room", "Game room"], ["waterfront", "Waterfront"],
    ["fire_pit", "Fire pit"], ["mini_golf", "Mini golf"], ["pickleball", "Pickleball"], ["pool_table", "Pool table"]];
  UW.AMEN_LABEL = { hot_tub: "Hot tub", pool: "Pool", game_room: "Game room", pickleball: "Pickleball", mini_golf: "Mini golf", sauna: "Sauna",
    playground: "Playground", waterfront: "Waterfront", pool_heater: "Heated pool", fire_pit: "Fire pit", pool_table: "Pool table",
    movie_theater: "Movie theater", golf_simulator: "Golf simulator", gym: "Gym", outdoor_dining_area: "Outdoor dining", pack_n_play_travel_crib: "Travel crib",
    crib: "Crib", lake_access: "Lake access" };
  UW.ICON_ORDER = ["pool", "pool_heater", "hot_tub", "game_room", "waterfront", "fire_pit", "mini_golf", "pickleball", "pool_table", "sauna", "playground"];
  const P = (d) => '<path d="' + d + '"/>';
  UW.ICON_SVG = {
    pool: P("M1 11c2 0 2-1.4 4-1.4S7 11 9 11s2-1.4 4-1.4 2 1.4 2 1.4M1 14c2 0 2-1.4 4-1.4S7 14 9 14s2-1.4 4-1.4 2 1.4 2 1.4M5 8.5V4a1.5 1.5 0 0 1 3 0M10 8.5V4a1.5 1.5 0 0 1 3 0M5 6.5h5"),
    pool_heater: P("M8 2a1.6 1.6 0 0 0-1.6 1.6v6.1a2.9 2.9 0 1 0 3.2 0V3.6A1.6 1.6 0 0 0 8 2zM8 7.5v4"),
    hot_tub: P("M1.5 8.5h13v2a3.2 3.2 0 0 1-3.2 3.2H4.7a3.2 3.2 0 0 1-3.2-3.2zM5 6V5.4M8 6V3.6M11 6V4.8"),
    game_room: P("M5 5h6a3.5 3.5 0 0 1 0 7c-1.3 0-1.9-1-3-1s-1.7 1-3 1a3.5 3.5 0 0 1 0-7zM4 8.5h2.6M5.3 7.2v2.6M10.6 8h.01M12 9.4h.01"),
    waterfront: P("M8 4.6V14M5.2 7h5.6M2.6 9.6c0 2.7 2.4 4.4 5.4 4.4s5.4-1.7 5.4-4.4M9.5 3a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"),
    fire_pit: P("M8 14c-2.7 0-4.4-1.7-4.4-4.1C3.6 7 6 6.1 6 2.5c1.9 1.2 2.5 2.9 2.3 4.4.9-.6 1.6-1.6 1.6-2.9 1.9 1.6 2.5 3.7 2.5 5.7 0 2.4-1.7 4.3-4.4 4.3z"),
    mini_golf: P("M5 14.5V1.8l7 3-7 3M2.5 14.5h6"),
    pickleball: P("M10.5 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8.8 9.4l4.7 5M12.8 2.6h.01"),
    pool_table: P("M14 8A6 6 0 1 1 2 8a6 6 0 0 1 12 0zM10.2 8a2.2 2.2 0 1 1-4.4 0 2.2 2.2 0 0 1 4.4 0z"),
    sauna: P("M4 14c-1-1.5 1-2.5 0-4s1-2.5 0-4M8 14c-1-1.5 1-2.5 0-4s1-2.5 0-4M12 14c-1-1.5 1-2.5 0-4s1-2.5 0-4"),
    playground: P("M3 14V3.5h3V14M3 7.5h3M6 5.5c4.5 0 3.8 8.5 8.5 8.5"),
  };
  UW.icon = (key, title, on) => '<span class="uw-ico' + (on === false ? " uw-ico--off" : "") + '" title="' + UW.esc(title || UW.AMEN_LABEL[key] || key) + '" role="img" aria-label="' +
    UW.esc((title || UW.AMEN_LABEL[key] || key) + (on === false ? ": no" : "")) + '"><svg viewBox="0 0 16 16" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' +
    (UW.ICON_SVG[key] || "") + "</svg></span>";
  UW.amenityIcons = (flags) => UW.ICON_ORDER.filter((k) => flags.has(k)).map((k) => UW.icon(k)).join("");

  UW.LOC_COLORS = { "Gulf-front": "#075646", "Beach walk": "#5f9e8f", "Bay / canal": "#d99132", "Inland": "#a8b2bd" };  // charts.js LOC_PALETTE
  UW.TIER_COLORS = { top10: "#d99132", top25: "#075646", rest: "#8b94a3" };                                           // charts.js CHART_PALETTE
  UW.TIER_LABEL = { top10: "Top 10% for its size", top25: "Top 11–25% for its size", rest: "Below the top 25% for its size" };
  UW.REV_BANDS = [[0, 60000, "Under $60k", "#c4d9d1"], [60000, 90000, "$60k–$90k", "#8fbcae"], [90000, 120000, "$90k–$120k", "#4f9883"],
    [120000, 160000, "$120k–$160k", "#1c6e58"], [160000, Infinity, "$160k+", "#043f35"]];
  UW.COC_TARGET = 0.04;
  UW.SCREEN = 0.20;
  UW.cocStatus = (v) => (!isNum(v) ? "none" : v >= UW.COC_TARGET ? "good" : v >= 0 ? "warn" : "bad");
  UW.COC_COLORS = { good: "#1B7A43", warn: "#b7791f", bad: "#b3261e", none: "#5A6B78" };
  UW.WATERFRONT_TYPES = ["Gulf-front", "Bay-canal", "None"];
  UW.WATERFRONT_LOC = { "Gulf-front": ["Gulf-front"], "Bay-canal": ["Bay / canal"], "None": ["Beach walk", "Inland"] };

  // ---------------------------------------------------------------------------
  // Data
  // ---------------------------------------------------------------------------
  UW.load = async function () {
    const get = (p) => fetch(p + "?v=" + UW.VERSION).then((r) => { if (!r.ok) throw new Error(p + ": " + r.status); return r.json(); });
    const [comps, shoreline, uw] = await Promise.all([get("data/comps.json"), get("data/shoreline.json"), get("data/underwritten.json")]);
    UW.data = { comps, shoreline, uw };
    UW.listings = comps.listings;
    UW.listings.forEach((l, i) => { l.i = i; l.flagSet = new Set(l.flags); });
    UW.byId = new Map(UW.listings.map((l) => [l.id, l]));
    UW.otherRooms = new Set(comps.otherRooms);
    UW.areas = comps.areas;
    UW.areaById = Object.fromEntries(comps.areas.map((a) => [a.id, a]));
    UWGeo.init(shoreline, UW.listings);
    UW.templates = uw.properties.flatMap((p) => p.versions.map((v) => ({ pid: p.id, label: v.label, file: v.file, street: p.street })));
    loadLocal();
  };
  UW.amortization = async function () {
    if (!UW._amort) UW._amort = await fetch("data/amortization.json?v=" + UW.VERSION).then((r) => r.json());
    return UW._amort;
  };
  UW.sourceCsv = (file) => fetch("underwriting/source_csv/" + encodeURIComponent(file) + "?v=" + UW.VERSION).then((r) => {
    if (!r.ok) throw new Error("Couldn't load " + file + " (" + r.status + ")");
    return r.text();
  });

  // ---------------------------------------------------------------------------
  // Saved edits (localStorage) layered over committed edits (data/underwritten_local.json)
  // ---------------------------------------------------------------------------
  UW.local = { listings: [], edits: {}, deleted: [] };
  UW.storageOk = true;
  function loadLocal() {
    try {
      const raw = window.localStorage.getItem(LS_KEY);
      if (raw) {
        const js = JSON.parse(raw);
        UW.local = { listings: js.listings || [], edits: js.edits || {}, deleted: js.deleted || [] };
      }
    } catch (e) {
      UW.storageOk = false;
    }
  }
  let saveTimer = null;
  UW.save = function () {
    clearTimeout(saveTimer);
    saveTimer = setTimeout(() => {
      try {
        window.localStorage.setItem(LS_KEY, JSON.stringify(UW.local));
        UW.storageOk = true;
      } catch (e) {
        if (UW.storageOk) UW.toast("Edits can't be saved in this browser (storage is blocked or full). Use Export to keep them.", "warn");
        UW.storageOk = false;
      }
      UW.emit("saved");
    }, 250);
  };
  const committed = () => UW.data.uw.committed || { listings: [], edits: {} };

  function propEdit(pid) {
    const c = (committed().edits[pid] || {}).property || {}, l = (UW.local.edits[pid] || {}).property || {};
    return Object.assign({}, c, l);
  }
  function verEdit(pid, label) {
    const c = ((committed().edits[pid] || {}).versions || {})[label], l = ((UW.local.edits[pid] || {}).versions || {})[label];
    if (l && l.reverted) return null;
    if (!c && !l) return null;
    return Object.assign({}, c || {}, l || {});
  }
  function localVer(pid, label) {
    const e = (UW.local.edits[pid] = UW.local.edits[pid] || {});
    e.versions = e.versions || {};
    if (e.versions[label] && e.versions[label].reverted) e.versions[label] = {};
    return (e.versions[label] = e.versions[label] || {});
  }

  // All new listings: committed ones (unless deleted here) overlaid by this browser's.
  function newListings() {
    const del = new Set(UW.local.deleted);
    const map = new Map();
    committed().listings.forEach((l) => { if (!del.has(l.id)) map.set(l.id, l); });
    UW.local.listings.forEach((l) => map.set(l.id, l));
    return [...map.values()];
  }
  function ownListing(id) {
    let l = UW.local.listings.find((x) => x.id === id);
    if (!l) {
      const c = committed().listings.find((x) => x.id === id);
      if (!c) return null;
      l = UW.clone(c);
      UW.local.listings.push(l);
    }
    return l;
  }

  // ---------------------------------------------------------------------------
  // Property models
  // ---------------------------------------------------------------------------
  UW.ui = { selected: null, versions: {}, expanded: new Set(), colorBy: "revenue", n: 12, radius: null, sort: "distance",
    layers: { areas: true, labels: true, shoreline: false, ghosts: true, uw: true, newl: true }, listSort: { key: "area", dir: 1 } };

  UW.parseNotes = function (text) {
    const t = text || "";
    const grab = (re) => { const m = t.match(re); return m ? m[1].trim() : null; };
    const bb = grab(/Bed\s*\/\s*Bath\s*\(projected\)\s*:\s*([^\n]*)/i), lot = grab(/Lot Size\s*\(sqft\)\s*:\s*([^\n]*)/i), size = grab(/Prop Size\s*\(sqft\)\s*:\s*([^\n]*)/i);
    const out = { bedBathText: bb, lotText: lot, sizeText: size, beds: null, baths: null, lot: null, size: null };
    const m = bb && bb.match(/^(\d+(?:\.\d+)?)\s*\/\s*(\d+(?:\.\d+)?)\s*(.*)$/);
    if (m) { out.beds = +m[1]; out.baths = +m[2]; out.bedBathComment = m[3].trim() || null; }
    [["lot", lot], ["size", size]].forEach(([k, s]) => { const n = (s || "").match(/^([\d,]+(?:\.\d+)?)\s*(.*)$/); if (n) { out[k] = +n[1].replace(/,/g, ""); out[k + "Comment"] = n[2].replace(/^[\s,]+|[\s,]+$/g, "") || null; } });
    const why = t.includes("Why This Property?") ? t.split("Why This Property?")[1] : "";
    out.why = why.split("\n").map((s) => s.trim()).filter((s) => s.startsWith("--")).map((s) => s.slice(2).replace(/^[\s,]+|[\s,]+$/g, "")).filter(Boolean);
    return out;
  };

  function placeFor(geo, notes, waterfront) {
    if (!geo) return null;
    return UWGeo.classify(geo.lat, geo.lng, notes, waterfront && waterfront !== "auto" ? waterfront : null);
  }

  function buildUnderwritten(base) {
    const pe = propEdit(base.id);
    const geo = pe.pin || base.geo;
    const versions = base.versions.map((v) => {
      const e = verEdit(base.id, v.label) || {};
      const inputs = e.inputs || v.inputs;
      const notes = e.notes != null ? e.notes : v.notes;
      const comps = e.comps || v.comps;
      const inputsEdited = !!e.inputs;
      return {
        label: v.label, file: v.file, files: v.files, number: v.number, url: v.url, preparedBy: v.preparedBy, sheet: v.sheet, layout: v.layout, checks: v.checks,
        base: v, notes, inputs, comps: comps.map((c) => Object.assign({}, c, UW.compStatus(c))), details: UW.parseNotes(notes),
        edited: { inputs: inputsEdited, notes: e.notes != null && e.notes !== v.notes, comps: !!e.comps },
        outputs: inputsEdited ? UWMath.compute(inputs) : UWMath.fromSheet(v.sheet), source: inputsEdited ? "recalculated" : "sheet",
      };
    });
    const def = versions.find((v) => v.label === base.defaultVersion);
    const waterfront = pe.waterfront || null;
    let place = base.place;
    if (pe.pin || pe.waterfront || (def && def.edited.notes)) place = placeFor(geo, def && def.notes, waterfront);
    if (place && !place.areaName) place.areaName = (UW.areaById[place.area] || {}).name;
    return { id: base.id, kind: "underwritten", street: base.street, address: base.address, url: base.url, zip: base.zip, geo, place,
      waterfront: waterfront || (place ? place.waterfrontDefault : "None"), versions, defaultVersion: base.defaultVersion, pinEdited: !!pe.pin,
      geoNote: base.geo ? (base.geo.approximate ? "Census geocoder matched a shortened address" : "US Census geocoder") : null };
  }

  function buildNew(l) {
    const notes = l.notes || "";
    const inputs = l.inputs;
    const place = placeFor(l.pin, notes, l.waterfront);
    if (place) place.areaName = (UW.areaById[place.area] || {}).name;
    const v = { label: "Draft", file: null, files: [], url: l.url, sheet: null, checks: [], base: null, notes, inputs,
      comps: (l.comps || []).map((c) => Object.assign({}, c, UW.compStatus(c))), details: UW.parseNotes(notes),
      edited: { inputs: true, notes: false, comps: false }, outputs: UWMath.compute(inputs), source: "recalculated" };
    return { id: l.id, kind: l.promoted ? "promoted" : "new", street: l.street, address: l.address, url: l.url, zip: l.zip, geo: l.pin || null, place,
      waterfront: l.waterfront && l.waterfront !== "auto" ? l.waterfront : place ? place.waterfrontDefault : "None", versions: [v], defaultVersion: "Draft",
      listing: l, local: !!UW.local.listings.find((x) => x.id === l.id), geoNote: l.pin ? (l.pin.source === "manual" ? "placed by hand" : "OpenStreetMap (Nominatim)" + (l.pin.approximate ? ", street only" : "")) : null };
  }

  UW.properties = function () {
    return UW.data.uw.properties.map(buildUnderwritten).concat(newListings().map(buildNew));
  };
  UW.property = (pid) => {
    const b = UW.data.uw.properties.find((p) => p.id === pid);
    if (b) return buildUnderwritten(b);
    const l = newListings().find((x) => x.id === pid);
    return l ? buildNew(l) : null;
  };
  UW.activeVersion = (p) => p.versions.find((v) => v.label === (UW.ui.versions[p.id] || p.defaultVersion)) || p.versions[p.versions.length - 1];

  // ---------------------------------------------------------------------------
  // Mutations
  // ---------------------------------------------------------------------------
  UW.isNew = (pid) => !UW.data.uw.properties.some((p) => p.id === pid);

  UW.setInputs = function (pid, label, inputs) {
    if (UW.isNew(pid)) { ownListing(pid).inputs = inputs; }
    else {
      const base = UW.data.uw.properties.find((p) => p.id === pid).versions.find((v) => v.label === label);
      const e = localVer(pid, label);
      if (same(inputs, base.inputs)) delete e.inputs; else e.inputs = inputs;
      const c = ((committed().edits[pid] || {}).versions || {})[label];
      if (!e.inputs && c && c.inputs) e.inputs = UW.clone(base.inputs);  // back to the sheet over a committed edit
    }
    UW.save(); UW.emit("property", pid);
  };
  UW.setNotes = function (pid, label, notes) {
    if (UW.isNew(pid)) ownListing(pid).notes = notes;
    else localVer(pid, label).notes = notes;
    UW.save(); UW.emit("property", pid);
  };
  UW.setComps = function (pid, label, comps, opts) {
    const clean = comps.slice(0, 15).map((c) => ({ url: c.url, id: c.id, revenue: c.revenue, bedrooms: c.bedrooms, sleeps: c.sleeps, adr: c.adr,
      occupancy: c.occupancy, flags: Object.assign({}, c.flags), notes: c.notes || "" }));
    if (UW.isNew(pid)) ownListing(pid).comps = clean;
    else localVer(pid, label).comps = clean;
    UW.save();
    if (opts && opts.quiet) return;  // typing in a comp's notes: no re-render
    UW.emit("property", pid); UW.emit("comps", pid);
  };
  UW.editSource = function (pid, label) {
    const l = ((UW.local.edits[pid] || {}).versions || {})[label];
    if (l && !l.reverted && Object.keys(l).length) return "browser";
    const c = ((committed().edits[pid] || {}).versions || {})[label];
    return c && !(l && l.reverted) ? "committed" : null;
  };
  UW.setPropertyField = function (pid, key, value) {
    if (UW.isNew(pid)) {
      const l = ownListing(pid);
      if (key === "pin") l.pin = value; else if (key === "waterfront") l.waterfront = value;
    } else {
      const e = (UW.local.edits[pid] = UW.local.edits[pid] || {});
      e.property = e.property || {};
      if (value == null) delete e.property[key]; else e.property[key] = value;
    }
    UW.save(); UW.emit("property", pid); UW.emit("places");
  };
  UW.revert = function (pid, label) {
    const e = (UW.local.edits[pid] = UW.local.edits[pid] || {});
    e.versions = e.versions || {};
    e.versions[label] = { reverted: true };
    UW.save(); UW.emit("property", pid); UW.emit("comps", pid);
  };
  UW.hasEdits = (pid, label) => !!verEdit(pid, label);

  UW.addListing = function (l) {
    UW.local.listings.push(l);
    UW.local.deleted = UW.local.deleted.filter((x) => x !== l.id);
    UW.save(); UW.emit("listings");
  };
  UW.updateListing = function (id, patch) {
    Object.assign(ownListing(id), patch);
    UW.save(); UW.emit("property", id); UW.emit("places");
  };
  UW.deleteListing = function (id) {
    UW.local.listings = UW.local.listings.filter((x) => x.id !== id);
    if (committed().listings.some((x) => x.id === id) && !UW.local.deleted.includes(id)) UW.local.deleted.push(id);
    if (UW.ui.selected === id) UW.select(null);
    UW.save(); UW.emit("listings");
  };

  // Everything needed to reproduce this browser's state, for data/underwritten_local.json.
  UW.exportLocal = function () {
    const edits = {};
    const pids = new Set(Object.keys(committed().edits).concat(Object.keys(UW.local.edits)));
    pids.forEach((pid) => {
      if (UW.isNew(pid)) return;
      const out = {};
      const pe = propEdit(pid);
      if (Object.keys(pe).length) out.property = pe;
      const base = UW.data.uw.properties.find((p) => p.id === pid);
      if (!base) return;
      base.versions.forEach((v) => {
        const e = verEdit(pid, v.label);
        if (!e) return;
        const clean = {};
        if (e.inputs && !same(e.inputs, v.inputs)) clean.inputs = e.inputs;
        if (e.notes != null && e.notes !== v.notes) clean.notes = e.notes;
        if (e.comps) clean.comps = e.comps;
        if (Object.keys(clean).length) (out.versions = out.versions || {})[v.label] = clean;
      });
      if (Object.keys(out).length) edits[pid] = out;
    });
    return { format: "galveston-underwritten-local", version: 1, exported: new Date().toISOString().slice(0, 10),
      note: "Commit as data/underwritten_local.json, then run scripts/build_underwritten.py", listings: newListings(), edits };
  };
  UW.importLocal = function (js) {
    if (!js || (js.format && js.format !== "galveston-underwritten-local") || !Array.isArray(js.listings || []) || typeof (js.edits || {}) !== "object") throw new Error("This isn't an Underwritten Properties export.");
    (js.listings || []).forEach((l) => {
      if (!l.id || !l.inputs) throw new Error("A listing in the file is missing its id or inputs.");
      UW.local.listings = UW.local.listings.filter((x) => x.id !== l.id).concat([l]);
      UW.local.deleted = UW.local.deleted.filter((x) => x !== l.id);
    });
    Object.entries(js.edits || {}).forEach(([pid, e]) => { UW.local.edits[pid] = UW.clone(e); });
    UW.save(); UW.emit("listings"); UW.emit("places");
    return { listings: (js.listings || []).length, edits: Object.keys(js.edits || {}).length };
  };
  UW.clearLocal = function () {
    UW.local = { listings: [], edits: {}, deleted: [] };
    UW.save(); UW.emit("listings"); UW.emit("places");
  };

  // ---------------------------------------------------------------------------
  // Comps against the current workbook
  // ---------------------------------------------------------------------------
  const round2 = (v) => Math.round(v * 100) / 100;
  UW.compId = (c) => c.id || ((String(c.url || "").match(/rooms\/(\d+)/) || [])[1] || null);
  UW.compStatus = function (c) {
    const id = UW.compId(c);
    if (!id) return { status: "unrecognised", changes: [], id: null };
    const cur = UW.byId.get(id);
    if (!cur) return { status: UW.otherRooms.has(id) ? "other-room" : "missing", changes: [], id };
    const ch = [];
    const cmp = (field, label, old, neu, tol, fmt) => { if (old == null || neu == null || Math.abs(old - neu) > tol) ch.push({ field, label, sheet: old, current: neu, fmt }); };
    cmp("revenue", "Revenue", c.revenue, cur.revenue, 0.51, "money");
    cmp("bedrooms", "Bedrooms", c.bedrooms, cur.bedrooms, 0.01, "num");
    cmp("sleeps", "Sleeps", c.sleeps, cur.sleeps, 0.01, "num");
    cmp("adr", "Nightly rate", c.adr, round2(cur.adr), 0.006, "money2");
    // Several sheets typed occupancy to one decimal (57.9 for 57.93): within 0.05 points is the same value.
    cmp("occupancy", "Occupancy", c.occupancy == null ? null : round2(c.occupancy * 100), round2(cur.occ * 100), 0.051, "pctpts");
    UWCsv.SHEET_FLAGS.forEach((f) => cmp("HAS_" + f, UW.AMEN_LABEL[f], c.flags && c.flags[f] ? 1 : 0, cur.flagSet.has(f) ? 1 : 0, 0, "flag"));
    return { status: ch.length ? "changed" : "match", changes: ch, id };
  };
  UW.compFromListing = function (l, notes) {
    return { url: l.url, id: l.id, revenue: l.revenue, bedrooms: l.bedrooms, sleeps: l.sleeps, adr: round2(l.adr), occupancy: Math.round(l.occ * 10000) / 10000,
      flags: Object.fromEntries(UWCsv.SHEET_FLAGS.map((f) => [f, l.flagSet.has(f) ? 1 : 0])), notes: notes == null ? UW.compNote(l) : notes };
  };
  // Factual starting note from the workbook (editable; no judgement added).
  UW.compNote = function (l) {
    const am = ["pool", "pool_heater", "hot_tub", "game_room", "fire_pit", "mini_golf", "pickleball", "pool_table"].filter((k) => l.flagSet.has(k))
      .map((k) => (k === "pool_heater" ? "heated pool" : UW.AMEN_LABEL[k].toLowerCase()));
    if (am.includes("heated pool")) am.splice(am.indexOf("pool"), 1);
    return UW.fmt.beds(l.bedrooms) + "/" + UW.fmt.num(l.baths) + "BA" + (am.length ? " - " + am.join(" + ") : "") + "; " + l.loc + ", " + UW.areaById[l.area].name;
  };

  UW.compStats = function (p, v) {
    const revs = v.comps.map((c) => c.revenue).filter(isNum).sort((a, b) => a - b);
    const q = (p_) => { if (!revs.length) return null; const h = (revs.length - 1) * p_, lo = Math.floor(h); return revs[lo] + (revs[Math.min(lo + 1, revs.length - 1)] - revs[lo]) * (h - lo); };
    const known = v.comps.map((c) => UW.byId.get(UW.compId(c))).filter(Boolean);
    return { n: v.comps.length, p25: q(0.25), median: q(0.5), p75: q(0.75), max: revs.length ? revs[revs.length - 1] : null, min: revs.length ? revs[0] : null, known: known.length,
      sameArea: p.place ? known.filter((l) => l.area === p.place.area).length : null, sameLoc: p.place ? known.filter((l) => l.loc === p.place.loc).length : null };
  };

  // ---------------------------------------------------------------------------
  // Filters (apply to the Airbnb dots and the nearest-comp list) + URL hash
  // ---------------------------------------------------------------------------
  UW.defaultFilters = () => ({ minRev: 90000, maxRev: null, beds: [], minSleeps: null, minBaths: null, am: {}, loc: [], area: [], zone: "", sizeTop: [], quality: [], fav: "" });
  UW.ui.filters = UW.defaultFilters();
  UW.bedBucket = (b) => (b <= 1 ? 1 : b >= 7 ? 7 : Math.round(b));
  UW.matches = function (l, f) {
    f = f || UW.ui.filters;
    if (f.minRev != null && l.revenue < f.minRev) return false;
    if (f.maxRev != null && l.revenue > f.maxRev) return false;
    if (f.beds.length && !f.beds.includes(UW.bedBucket(l.bedrooms))) return false;
    if (f.minSleeps != null && l.sleeps < f.minSleeps) return false;
    if (f.minBaths != null && l.baths < f.minBaths) return false;
    for (const k in f.am) { const v = f.am[k]; if (v === 1 && !l.flagSet.has(k)) return false; if (v === -1 && l.flagSet.has(k)) return false; }
    if (f.loc.length && !f.loc.includes(l.loc)) return false;
    if (f.area.length && !f.area.includes(l.area)) return false;
    if (f.zone && (f.zone === "Town") !== l.town) return false;
    if (f.sizeTop.length && !f.sizeTop.includes(l.sizeTop)) return false;
    if (f.quality.length && !f.quality.includes(l.quality)) return false;
    if (f.fav && (f.fav === "yes") !== !!l.fav) return false;
    return true;
  };
  UW.applyFilters = function () {
    UW.matchSet = new Set(UW.listings.filter((l) => UW.matches(l)).map((l) => l.id));
    UW.writeHash();
    UW.emit("filters");
  };
  UW.setFilters = function (patch) { Object.assign(UW.ui.filters, patch); UW.applyFilters(); };
  UW.resetFilters = function () { UW.ui.filters = UW.defaultFilters(); UW.applyFilters(); };
  UW.matchProperty = function (p) {
    const v = UW.activeVersion(p);
    const b = v.details.beds != null ? v.details.beds : p.listing && p.listing.facts ? p.listing.facts.projBeds || p.listing.facts.beds : null;
    const f = UW.defaultFilters();
    if (b != null) f.beds = [b - 1, b, b + 1].filter((x) => x >= 1).map(UW.bedBucket).filter((x, i, a) => a.indexOf(x) === i);
    if (p.place) f.zone = p.place.zone;
    f.loc = (UW.WATERFRONT_LOC[p.waterfront] || []).slice();
    UW.ui.filters = f;
    UW.applyFilters();
  };
  UW.countActiveFilters = function () {
    const f = UW.ui.filters, d = UW.defaultFilters();
    let n = 0;
    if (f.minRev !== d.minRev) n++;
    if (f.maxRev != null) n++;
    ["beds", "loc", "area", "sizeTop", "quality"].forEach((k) => { if (f[k].length) n++; });
    ["minSleeps", "minBaths"].forEach((k) => { if (f[k] != null) n++; });
    n += Object.values(f.am).filter(Boolean).length;
    if (f.zone) n++;
    if (f.fav) n++;
    return n;
  };

  // Nearest listings to a property among those passing the filters.
  UW.nearest = function (p) {
    if (!p || !p.geo) return [];
    const out = [];
    UW.listings.forEach((l) => {
      if (!UW.matchSet.has(l.id)) return;
      const d = UWGeo.miles(p.geo.lat, p.geo.lng, l.lat, l.lng);
      if (UW.ui.radius != null && d > UW.ui.radius) return;
      out.push({ l, d });
    });
    out.sort((a, b) => a.d - b.d);
    return out.slice(0, UW.ui.n).map((x, i) => Object.assign(x, { rank: i + 1 }));
  };

  UW.select = function (pid, opts) {
    UW.ui.selected = pid;
    if (pid) {
      const p = UW.property(pid);
      if (!p) UW.ui.selected = null;
    }
    UW.writeHash();
    UW.emit("select", Object.assign({ pid: UW.ui.selected }, opts || {}));
  };
  UW.setVersion = function (pid, label) {
    UW.ui.versions[pid] = label;
    UW.writeHash();
    UW.emit("property", pid); UW.emit("comps", pid); UW.emit("places");
  };

  const LIST = (s) => (s ? s.split(",").filter(Boolean) : []);
  UW.writeHash = function () {
    if (UW._hashLock) return;
    const f = UW.ui.filters, d = UW.defaultFilters(), q = new URLSearchParams();
    if (UW.ui.selected) q.set("p", UW.ui.selected);
    if (UW.ui.selected && UW.ui.versions[UW.ui.selected]) q.set("v", UW.ui.versions[UW.ui.selected]);
    if (f.minRev !== d.minRev) q.set("min", f.minRev == null ? "" : f.minRev);
    if (f.maxRev != null) q.set("max", f.maxRev);
    if (f.beds.length) q.set("beds", f.beds.join(","));
    if (f.minSleeps != null) q.set("sleeps", f.minSleeps);
    if (f.minBaths != null) q.set("baths", f.minBaths);
    const am = Object.entries(f.am).filter(([, v]) => v).map(([k, v]) => (v === 1 ? "+" : "-") + k);
    if (am.length) q.set("am", am.join(","));
    if (f.loc.length) q.set("loc", f.loc.join(","));
    if (f.area.length) q.set("area", f.area.join(","));
    if (f.zone) q.set("zone", f.zone);
    if (f.sizeTop.length) q.set("tier", f.sizeTop.join(","));
    if (f.quality.length) q.set("dq", f.quality.join(","));
    if (f.fav) q.set("fav", f.fav);
    if (UW.ui.colorBy !== "revenue") q.set("color", UW.ui.colorBy);
    if (UW.ui.n !== 12) q.set("n", UW.ui.n);
    if (UW.ui.radius != null) q.set("r", UW.ui.radius);
    if (UW.ui.sort !== "distance") q.set("sort", UW.ui.sort);
    const s = q.toString().replace(/%2C/g, ",").replace(/%2F/g, "/").replace(/\+/g, "%20");
    try { history.replaceState(null, "", s ? "#" + s : location.pathname + location.search); } catch (e) { /* file:// */ }
  };
  UW.readHash = function () {
    const q = new URLSearchParams(location.hash.replace(/^#/, ""));
    const f = UW.defaultFilters();
    const n = (k) => (q.get(k) === "" || q.get(k) == null || isNaN(+q.get(k)) ? null : +q.get(k));
    if (q.has("min")) f.minRev = n("min");
    if (q.has("max")) f.maxRev = n("max");
    f.beds = LIST(q.get("beds")).map(Number).filter((x) => x >= 1 && x <= 7);
    f.minSleeps = n("sleeps"); f.minBaths = n("baths");
    LIST(q.get("am")).forEach((s) => { const k = s.slice(1); if (UW.AMENITIES.some((a) => a[0] === k)) f.am[k] = s[0] === "-" ? -1 : 1; });
    f.loc = LIST(q.get("loc")).filter((x) => UW.data.comps.locOrder.includes(x));
    f.area = LIST(q.get("area")).filter((x) => UW.areaById[x]);
    f.zone = ["Town", "West End"].includes(q.get("zone")) ? q.get("zone") : "";
    f.sizeTop = LIST(q.get("tier")).filter((x) => ["top10", "top25", "rest"].includes(x));
    f.quality = LIST(q.get("dq")).filter((x) => ["Good", "Possibly Good"].includes(x));
    f.fav = ["yes", "no"].includes(q.get("fav")) ? q.get("fav") : "";
    UW.ui.filters = f;
    if (["revenue", "tier", "area", "loc"].includes(q.get("color"))) UW.ui.colorBy = q.get("color");
    if (n("n")) UW.ui.n = Math.max(1, Math.min(50, n("n")));
    UW.ui.radius = n("r");
    if (q.get("sort") === "revenue") UW.ui.sort = "revenue";
    const pid = q.get("p");
    if (pid && UW.property(pid)) {
      UW.ui.selected = pid;
      if (q.get("v") && UW.property(pid).versions.some((v) => v.label === q.get("v"))) UW.ui.versions[pid] = q.get("v");
    }
  };

  // ---------------------------------------------------------------------------
  // Small UI utilities
  // ---------------------------------------------------------------------------
  // A re-render that starts while a pointer is down (a field's "change" fires on
  // the mousedown that blurs it) would swap out the button being clicked and
  // lose the click. Such renders wait until the click has been delivered.
  let pointerDown = false, pending = [];
  document.addEventListener("pointerdown", () => { pointerDown = true; }, true);
  document.addEventListener("pointerup", () => {
    pointerDown = false;
    const run = pending; pending = [];
    if (run.length) setTimeout(() => run.forEach((fn) => fn()), 0);
  }, true);
  UW.afterPointer = (fn) => { if (pointerDown) pending.push(fn); else fn(); };
  UW.toast = function (msg, kind) {
    let host = document.getElementById("uw-toasts");
    if (!host) { host = document.createElement("div"); host.id = "uw-toasts"; host.className = "uw-toasts"; host.setAttribute("role", "status"); host.setAttribute("aria-live", "polite"); document.body.appendChild(host); }
    const t = document.createElement("div");
    t.className = "uw-toast" + (kind ? " uw-toast--" + kind : "");
    t.textContent = msg;
    host.appendChild(t);
    setTimeout(() => t.classList.add("is-out"), kind === "warn" ? 6000 : 2600);
    setTimeout(() => t.remove(), kind === "warn" ? 6500 : 3100);
  };
  UW.copy = async function (text, what) {
    try {
      await navigator.clipboard.writeText(text);
    } catch (e) {
      const ta = document.createElement("textarea");
      ta.value = text; ta.setAttribute("readonly", ""); ta.style.position = "fixed"; ta.style.opacity = "0";
      document.body.appendChild(ta); ta.select();
      let ok = false;
      try { ok = document.execCommand("copy"); } catch (e2) { ok = false; }
      ta.remove();
      if (!ok) { UW.toast("Couldn't copy. Your browser blocked clipboard access.", "warn"); return false; }
    }
    UW.toast("Copied " + what);
    return true;
  };
  UW.download = function (filename, text, type) {
    const blob = new Blob([text], { type: type || "text/csv;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => { URL.revokeObjectURL(a.href); a.remove(); }, 500);
  };
})();
