"""
Generate the webpage's computed data from the overview notebook's outputs, so
no number on the page is hand-copied:

  ../notebooks/region_stats.json            -> js/region_data.js
  ../notebooks/<slug>_overview_map.html     -> assets/overview/<slug>_overview_map.html
  the market workbook (via market_common)   -> data/listings.json

Run the notebook first (python ../notebooks/build_overview_notebook.py, then
nbconvert --execute), then this script, from anywhere:
    python scripts/generate_webpage_data.py
Do not hand-edit js/region_data.js or data/listings.json.
This script is identical across markets; market specifics come from
../notebooks/market_common.py.
"""
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NB = ROOT.parent / "notebooks"
sys.path.insert(0, str(NB))
import market_common as mc  # noqa: E402

s = json.loads((NB / "region_stats.json").read_text())


def r0(x):
    return None if x is None else round(float(x))


def r2(x):
    return None if x is None else round(float(x), 2)


def cell(c):
    if not c or not c.get("n"):
        return {"n": 0}
    return {"n": c["n"], "median": r0(c["median"]), "idx": r2(c["idx"]), "adr": r0(c["adr"]), "occ": round(c["occ"]),
            "topShare": round(c["top_share"])}


areas = [{
    "id": mc.AREA_SHORT[a], "name": a, "sub": mc.AREA_SUB[a], "color": mc.AREA_COLORS[a],
    "n": int(s["areas"][a]["N"]), "medianRev": r0(s["areas"][a]["median_rev"]), "idx": r2(s["areas"][a]["idx"]),
    "adr": r0(s["areas"][a]["median_adr"]), "occ": round(s["areas"][a]["median_occ"]),
    "top10N": int(s["areas"][a]["top10_n"]), "topForSize": round(s["areas"][a]["top_for_size_rate"]),
    "smallShare": round(s["areas"][a]["small_share"]), "bigShare": round(s["areas"][a]["big_share"]),
    "lat": round(s["areas"][a]["lat"], 4), "lng": round(s["areas"][a]["lng"], 4),
    "bySize": {sz: cell(c) for sz, c in s["area_size"][a].items()},
    "locMix": s["loc_mix"][a],
} for a in s["area_order"]]


def demo(rows):
    return [{"label": b["label"], "n": b["n"], "kids": b["pct_stayed_with_kids"], "group": b["pct_group_trip"],
             "pet": b["pct_stayed_with_a_pet"], "other": b["pct_other_reviews"]} for b in rows]


payload = {
    "REVENUE_DISTRIBUTION": {
        "totalCount": s["n"], "medianRevenue": r0(s["median"]), "p75": round(s["p75"], 1), "p90": round(s["p90"], 1),
        "histogram": s["histogram"],
    },
    "MARKET_STATS": {
        "market": s["market"], "snapshot": s["snapshot"], "n": s["n"], "median": r0(s["median"]), "p75": r0(s["p75"]),
        "p90": r0(s["p90"]), "max": r0(s["max"]), "medianAdr": r0(s["median_adr"]), "medianOcc": round(s["median_occ"] * 100),
        "medianRating": s["median_rating"], "bedroomMix": s["bedroom_mix"],
    },
    "DEMOGRAPHICS": {
        "marketWide": {"n": s["n"], "kids": s["demographics_market"]["pct_stayed_with_kids"],
                       "group": s["demographics_market"]["pct_group_trip"],
                       "pet": s["demographics_market"]["pct_stayed_with_a_pet"],
                       "other": s["demographics_market"]["pct_other_reviews"]},
        "byBedroom": demo(s["demographics_by_bedroom"]),
        "byLoc": demo(s["demographics_by_loc"]),
        "byArea": demo(s["demographics_by_area"]),
    },
    "LOCATION": {
        "sizes": s["size_order"], "locs": s["loc_order"], "locName": s["loc_name"], "locDef": s["loc_def"],
        "distLabel": s["dist_label"],
        "ladder": [{"size": r["size"], "n": int(r["N"]), "share": round(r["share"]), "median": r0(r["median"]),
                    "p25": r0(r["p25"]), "p75": r0(r["p75"]), "adr": r0(r["adr"]), "occ": round(r["occ"]),
                    "sleeps": r["sleeps"], "baths": r["baths"], "top10N": int(r["top10_n"]),
                    "top25Rate": round(r["top25_rate"]), "revPerBr": r0(r["rev_per_br"])} for r in s["ladder"]],
        "top10BySize": s["top10_by_size"],
        "locSize": {sz: {l: cell(c) for l, c in row.items()} for sz, row in s["loc_size"].items()},
        "areas": areas,
        "drivers": [{"driver": d["driver"], "kind": d["kind"], "nWith": d["n_with"], "nWithout": d["n_without"],
                     "topWith": round(d["top_with"]), "topWithout": round(d["top_without"]),
                     "idxWith": r2(d["idx_with"]), "idxWithout": r2(d["idx_without"])} for d in s["drivers"]],
        "amenBySize": {a: {sz: {"nWith": v["with_n"], "idxWith": r2(v["idx_with"]), "idxWithout": r2(v["idx_without"])}
                           for sz, v in d.items()} for a, d in s["amen_by_size"].items()},
        "bestBySize": s["best_by_size"],
    },
}

out = ["/**", " * AUTO-GENERATED by scripts/generate_webpage_data.py from",
       f" * ../notebooks/region_stats.json ({mc.SLUG}_overview.ipynb). Do not hand-edit.", " */"]
for k, v in payload.items():
    out.append(f"const {k} = {json.dumps(v, ensure_ascii=False)};")
(ROOT / "js" / "region_data.js").write_text("\n".join(out) + "\n")

(ROOT / "assets" / "overview").mkdir(parents=True, exist_ok=True)
shutil.copy(NB / f"{mc.SLUG}_overview_map.html", ROOT / "assets" / "overview" / f"{mc.SLUG}_overview_map.html")

df, P75, P90 = mc.load()
listings = [{
    "id": str(r["Property ID"]), "title": str(r["Listing_Title"]), "url": str(r["Listing URL"]),
    "bedrooms": float(r["Bedrooms"]), "size": r["size"], "revenue": float(r["Revenue Potential"]), "adr": float(r["ADR"]),
    "occupancy": float(r["Occupancy"]), "lat": float(r["Lat"]), "lng": float(r["Long"]),
    "area": mc.AREA_SHORT[r["Area"]], "loc": r["loc"], "vsSize": round(float(r["idx"]), 3), "sizeTier": r["size_tier"],
    "tier": {"Top 10%": "top10", "Top 25%": "top25"}.get(r["tier"], "bottom75"),
} for _, r in df.iterrows()]
(ROOT / "data").mkdir(exist_ok=True)
(ROOT / "data" / "listings.json").write_text(json.dumps({
    "generatedFrom": f"{mc.XLSX.name} (Cleaned_Data sheet)", "n": len(listings),
    "marketWideThresholds": {"p75": round(float(P75), 2), "p90": round(float(P90), 2)}, "listings": listings}))
print(f"wrote js/region_data.js, assets/overview/{mc.SLUG}_overview_map.html, data/listings.json ({len(listings)} listings)")
